development: &default
  adapter: postgresql
  database: link_saver_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE", "link_saver_test") %>
  host:     <%= ENV.fetch("PG_HOST", "localhost") %>
  username: <%= ENV.fetch("PG_USER", nil) %>
  password: <%= ENV.fetch("PG_PASSWORD", nil) %>
  port:     <%= ENV.fetch("PG_PORT", 5432) %>

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
